# Generated by Django 6.1.dev20260419192813 on 2026-04-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
